### ISSUE TITLE
From where download base.ova?

### ISSUE THREAD

**Issue by JohnVeness** [frappe/erpnext-vm#6]
From where, exactly, do you download base.ova?

**Comment by Thunderbottom** [comment]
you can download VM images here: https://erpnext.org/get-started

**Comment by JohnVeness** [comment]
Hi, thanks, but you misunderstand me. I don't mean how do you download the built images, I mean what is the source for the base.ova that Frappe use to build their images with packer, ansible, etc?

**Comment by Thunderbottom** [comment]
oh, i'm sorry. we've moved the scripts to the [bench](https://github.com/frappe/bench) repository, particularly the [vm folder](https://github.com/frappe/bench/tree/develop/vm) has all of the packer and vagrant build scripts.

**Comment by JohnVeness** [comment]
Ah right, many thanks. Maybe the readme could be updated in this repo to say that this is deprecated, and to point to that new folder?
